# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=45)),
                ('quote', models.TextField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('fav_id', models.ManyToManyField(related_name='usertofav', to='login_reg.Users')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertoquote', to='login_reg.Users')),
            ],
            managers=[
                ('usermanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
