# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170127_2156'),
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='coursetake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursetouser', to='courses.Courses'),
        ),
    ]
