# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_users_coursetake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='coursetake',
        ),
    ]
