# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='master_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterofmessage', to='login_reg.Users'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userofmessage', to='login_reg.Users'),
        ),
    ]
