# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_users_description'),
        ('thewall', '0003_auto_20170201_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='user_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userofmessage', to='login_reg.Users'),
        ),
    ]
