# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 22:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0005_auto_20170201_2047'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comments',
            managers=[
                ('usermanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
