# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170126_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userstocourses', to='login_reg.Users'),
        ),
    ]
