# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170126_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_reg.Users'),
        ),
    ]
