# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_remove_users_coursetake'),
        ('courses', '0007_auto_20170127_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userstocourses', to='login_reg.Users'),
        ),
    ]
