# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_remove_users_coursetake'),
        ('courses', '0008_courses_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='account',
        ),
        migrations.AddField(
            model_name='courses',
            name='account',
            field=models.ManyToManyField(null=True, related_name='userstocourses', to='login_reg.Users'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
